### ISSUE TITLE
As a user, I want the tool to have the same name everywhere.

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/OpenSC-GUI#2]
At the moment we have different names of the tools. 
- window title is "CNS Card Control"
- app name in installer is "buergerkarte"
- project name is "OpenSC GUI"
- ...

There has to be a single name used throughout the whole project. I suggest to stick to the project name "OpenSC GUI" until we find maybe a more user friendly name.

**Comment by mwallnoefer** [comment]
This has been adressed: The tool is now always called **Buergerkarte**, the project's name remains **OpenSC GUI** (also for GitHub).
